### GET request to example server
PATCH http://localhost:4002/user/customer/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NTMxOTIxNjIsImV4cCI6MjA1MzE5MjE2MiwicGhvbmVOdW1iZXIiOiIyMzQyMzQyMzQzIiwicmVnaXN0ZXJlZE9uIjoxNzUzMTg1MjUyMjExLCJhdXRob3JpdGllcyI6WyJST0xFX0NVU1RPTUVSIl0sImZpcnN0TmFtZSI6Ilpvcm8iLCJlbWFpbCI6Inpvcm9AeW9wbWFpbC5jb20iLCJpc0RlbGV0ZWQiOmZhbHNlLCJsYXN0TmFtZSI6IlJvcm9ub2EifQ.HvxoVgsYaeDWhHDALIKpca4GcKdRA0W0mIIv43xol9k

{
  "firstName": "Zoro",
  "lastName": "Roro 111",
  "email": "zoro@yopmail.com",
  "phoneNumber": "1231231232"
}

###