### PATCH request request endpoint to update user profile
PATCH http://localhost:1110/api/v1/user/profile?roleType=ROLE_CUSTOMER
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NTU3MTc5NDgsImV4cCI6MjA1NTcxNzk0OCwiZW1haWwiOiJ6b3JvQHlvcG1haWwuY29tIiwiaXNEZWxldGVkIjpmYWxzZSwibGFzdE5hbWUiOiJSb3JvIDExMSIsInBob25lTnVtYmVyIjoiMTIzMTIzMTIzMiIsInJlZ2lzdGVyZWRPbiI6MTc1NTcwNzQwODkxNywiYXV0aG9yaXRpZXMiOlsiUk9MRV9DVVNUT01FUiJdLCJmaXJzdE5hbWUiOiJOZXcgWm9ybyJ9.CCrsdOq5bZ9qtUShcE9gl8KA1dbnhVTwl6HvBW72ZlM

{
  "firstName": "New Zoro",
  "lastName": "Roro 111",
  "email": "zoro@yopmail.com",
  "phoneNumber": "1231231232"
}

###

###
PATCH http://localhost:1110/api/v1/user/profile?roleType=ROLE_SELLER
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NTU3MTY0NTgsImV4cCI6MjA1NTcxNjQ1OCwicmVnaXN0ZXJlZE9uIjoxNzU1NzA3Nzc2OTYwLCJhdXRob3JpdGllcyI6WyJST0xFX1NFTExFUiJdLCJmaXJzdE5hbWUiOiJMdWZmeSIsImVtYWlsIjoibHVmZnlAeW9wbWFpbC5jb20iLCJpc0RlbGV0ZWQiOmZhbHNlLCJsYXN0TmFtZSI6Ik1vbmtleSIsInBob25lTnVtYmVyIjoiMjM0MjM0MjM0MyJ9.se7t9aJJWF7ZVgy8He8vmqjHApB83EQ6Ih3FJsEwjtA

{
  "firstName": "Luffy",
  "lastName": "v2",
  "email": "luffy@yopmail.com",
  "phoneNumber": "1231231232",
  "companyName": "Sunny"
}

###