### POST request endpoint to login user into the system.
POST http://localhost:1110/api/v1/authentication/users/login?roleType=ROLE_CUSTOMER
content-type: application/json

{
  "email" : "zoro@yopmail.com",
  "password": "passZoro"
}

###

###

POST http://localhost:1110/api/v1/authentication/users/login?roleType=ROLE_SELLER
content-type: application/json

{
  "email" : "luffy@yopmail.com",
  "password": "passLuffy"
}

###