### GET request to example server
POST http://localhost:1110/api/v1/authentication/users/register
Content-Type: application/json

{
  "firstName" : "Zoro",
  "lastName" : "Roronoa",
  "email" : "zoro@yopmail.com",
  "password" : "passZoro",
  "phoneNumber" : "2342342343"
}
###